import type { Workflow } from './types';

const baseBudget = (token_cap: number, cost_cap_usd: number, time_cap_min: number) => ({
  token_cap,
  cost_cap_usd,
  time_cap_min,
  tokens_used: 0,
  cost_used_usd: 0,
  time_used_sec: 0,
});

export const fallbackWorkflow: Workflow = {
  id: 'wf_competitive_analysis',
  title: '竞品分析模板 MVP',
  template_id: 'tpl_competitive_analysis',
  sla: 'P3D',
  rollback_policy: 'human_takeover',
  owner: 'u_yang',
  state: 'running',
  edges: [
    { from_id: 'wi_collect_competitors', to_id: 'wi_draft_report' },
    { from_id: 'wi_draft_report', to_id: 'wi_gap_analysis' },
  ],
  executors: [],
  nodes: [
    {
      id: 'wi_collect_competitors',
      title: '竞品信息收集',
      goal: '收集 3 个核心竞品的定位、功能、价格、目标客户和近期发布动态。',
      inputs: [{ type: 'template', uri: 'competitive-analysis-v0' }],
      expected_outputs: [{ type: 'table', format: 'markdown' }],
      acceptance_criteria: [
        { id: 'ac_1', label: '至少覆盖 3 个竞品', checked: true },
        { id: 'ac_2', label: '每个竞品包含功能/价格/客户维度', checked: false },
      ],
      tool_whitelist: ['web_search', 'browser_read', 'lark_doc'],
      budget: baseBudget(30000, 12, 90),
      assignee: {
        id: 'agent_research_01',
        name: 'Research Scout',
        type: 'agent',
        capabilities: [{ tag: '竞品调研', confidence: 0.92 }],
        current_load: 35,
        unit_cost: 0.08,
        success_rate: 0.87,
        rework_rate: 0.11,
        owner_user_id: 'u_yang',
        agent_spec: { kind: 'research' },
      },
      owner: 'u_yang',
      state: 'in_progress',
      priority: 'P0',
      trace_id: 'trace_collect_competitors',
      parent_workflow_id: 'wf_competitive_analysis',
      artifacts: [],
      rejection_history: [],
      risk_score: 0.2,
      updated_at: new Date().toISOString(),
    },
    {
      id: 'wi_draft_report',
      title: '竞品分析报告起草',
      goal: '基于调研材料生成一版可评审的竞品分析报告。',
      inputs: [{ type: 'workitem', id: 'wi_collect_competitors' }],
      expected_outputs: [{ type: 'doc', format: 'markdown' }],
      acceptance_criteria: [
        { id: 'ac_3', label: '包含摘要、对比矩阵、机会点', checked: false },
        { id: 'ac_4', label: '结论可被产品例会直接讨论', checked: false },
      ],
      tool_whitelist: ['lark_doc', 'template_engine'],
      budget: baseBudget(24000, 10, 60),
      assignee: {
        id: 'agent_draft_01',
        name: 'Draft Pilot',
        type: 'agent',
        capabilities: [{ tag: '报告起草', confidence: 0.9 }],
        current_load: 42,
        unit_cost: 0.1,
        success_rate: 0.84,
        rework_rate: 0.14,
        owner_user_id: 'u_yang',
        agent_spec: { kind: 'drafting' },
      },
      owner: 'u_yang',
      state: 'queued',
      priority: 'P1',
      trace_id: 'trace_draft_report',
      parent_workflow_id: 'wf_competitive_analysis',
      artifacts: [],
      rejection_history: [],
      risk_score: 0.1,
      updated_at: new Date().toISOString(),
    },
    {
      id: 'wi_gap_analysis',
      title: '机会点与风险分析',
      goal: '提炼产品差异化机会、上线风险与建议决策。',
      inputs: [{ type: 'workitem', id: 'wi_draft_report' }],
      expected_outputs: [{ type: 'decision_brief', format: 'json' }],
      acceptance_criteria: [
        { id: 'ac_5', label: '输出 Top 5 机会点', checked: false },
        { id: 'ac_6', label: '标注置信度和证据引用', checked: false },
      ],
      tool_whitelist: ['analysis_engine', 'lark_doc'],
      budget: baseBudget(20000, 8, 45),
      assignee: {
        id: 'agent_analysis_01',
        name: 'Insight Analyst',
        type: 'agent',
        capabilities: [{ tag: '差距分析', confidence: 0.89 }],
        current_load: 25,
        unit_cost: 0.12,
        success_rate: 0.9,
        rework_rate: 0.09,
        owner_user_id: 'u_yang',
        agent_spec: { kind: 'analysis' },
      },
      owner: 'u_yang',
      state: 'awaiting_decision',
      priority: 'P1',
      trace_id: 'trace_gap_analysis',
      parent_workflow_id: 'wf_competitive_analysis',
      decision_gate: true,
      artifacts: [],
      rejection_history: [],
      risk_score: 0.4,
      updated_at: new Date().toISOString(),
    },
  ],
};
